<?php return array (
  0 => 'CREATE TABLE `xiaozu_shoptype` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(250) NOT NULL COMMENT \'分类名\',
  `type` varchar(100) DEFAULT NULL COMMENT \'checkbox多选，radio单选，img图片，input输入框\',
  `parent_id` int(20) NOT NULL DEFAULT \'0\' COMMENT \'0表示导航明，1值\',
  `cattype` int(1) NOT NULL DEFAULT \'1\' COMMENT \'1外卖2订台3其他\',
  `is_search` int(1) NOT NULL DEFAULT \'0\' COMMENT \'0不是搜索关键字1搜索关键字\',
  `is_main` int(1) NOT NULL DEFAULT \'0\' COMMENT \'是否展示在店铺列表 0否1是\',
  `is_admin` int(1) NOT NULL DEFAULT \'0\' COMMENT \'设置类型0店铺1后台\',
  `instro` varchar(255) DEFAULT NULL COMMENT \'简单介绍\',
  `orderid` int(10) NOT NULL DEFAULT \'0\' COMMENT \'排序ID\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=218 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'51\',\'分类\',\'checkbox\',\'0\',\'0\',\'1\',\'1\',\'0\',\'\',\'6\')',
  2 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'76\',\'2\',\'0\',\'67\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  3 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'75\',\'美食外卖\',\'0\',\'51\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  4 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'114\',\'超市分类\',\'checkbox\',\'0\',\'1\',\'1\',\'1\',\'0\',\'\',\'0\')',
  5 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'58\',\'60分钟\',\'0\',\'57\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  6 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'59\',\'店铺图标\',\'img\',\'0\',\'0\',\'0\',\'1\',\'0\',\'\',\'0\')',
  7 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'148\',\'15\',\'0\',\'100\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  8 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'199\',\'土豪馆\',\'0\',\'51\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  9 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'68\',\'1\',\'0\',\'67\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  10 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'150\',\'44\',\'0\',\'149\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  11 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'73\',\'送药上门\',\'0\',\'51\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  12 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'72\',\'网站专送\',\'0\',\'51\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  13 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'84\',\'1\',\'0\',\'83\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  14 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'85\',\'2\',\'0\',\'83\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  15 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'90\',\'a\',\'0\',\'89\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  16 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'91\',\'b\',\'0\',\'89\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  17 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'92\',\'c\',\'0\',\'89\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  18 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'93\',\'d\',\'0\',\'89\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  19 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'95\',\'杂货铺\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  20 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'96\',\'水果店\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  21 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'146\',\'12\',\'0\',\'100\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  22 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'102\',\'干洗店\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  23 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'104\',\'大型综合生活超市\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  24 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'105\',\'便利店\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  25 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'106\',\'家政\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  26 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'107\',\'维修点\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  27 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'108\',\'保洁\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  28 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'109\',\'小时工\',\'0\',\'94\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  29 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'110\',\'鲜花蛋糕\',\'0\',\'51\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  30 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'111\',\'水果蔬菜\',\'0\',\'51\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  31 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'112\',\'甜点饮品\',\'0\',\'51\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  32 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'116\',\'杂货店\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  33 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'117\',\'综合商超\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  34 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'121\',\'优惠活动\',\'0\',\'120\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  35 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'122\',\'一天一\',\'0\',\'120\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  36 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'124\',\'30\',\'0\',\'123\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  37 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'147\',\'13\',\'0\',\'100\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  38 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'128\',\'自取\',\'0\',\'127\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  39 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'129\',\'到店吃\',\'0\',\'127\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  40 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'141\',\'五金店\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  41 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'131\',\'自取\',\'0\',\'130\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  42 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'132\',\'外卖\',\'0\',\'130\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  43 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'151\',\'55\',\'0\',\'149\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  44 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'143\',\'客房\',\'0\',\'142\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  45 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'144\',\'餐厅\',\'0\',\'142\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  46 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'197\',\'/upload/goods/20160110163203632.png\',\'0\',\'59\',\'0\',\'0\',\'0\',\'0\',\'超时赔付\',\'0\')',
  47 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'196\',\'/upload/goods/20160110163208191.png\',\'0\',\'59\',\'0\',\'0\',\'0\',\'0\',\'可用优惠卷\',\'0\')',
  48 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'195\',\'/upload/goods/20160110163214689.png\',\'0\',\'59\',\'0\',\'0\',\'0\',\'0\',\'满减\',\'0\')',
  49 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'159\',\'鮮花\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  50 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'161\',\'家政\',\'0\',\'160\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  51 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'162\',\'美容\',\'0\',\'160\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  52 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'163\',\'美体\',\'0\',\'160\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  53 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'164\',\'洗车\',\'0\',\'160\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  54 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'166\',\'家政\',\'0\',\'165\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  55 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'167\',\'美体\',\'0\',\'165\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  56 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'168\',\'美容\',\'0\',\'165\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  57 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'169\',\'上门洗车\',\'0\',\'165\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  58 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'170\',\'上门厨师\',\'0\',\'165\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  59 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'172\',\'跑腿\',\'0\',\'165\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  60 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'194\',\'酒店\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  61 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'174\',\'董子巷\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  62 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'175\',\'高地世纪城\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  63 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'176\',\'傻吃街\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  64 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'177\',\'东风路\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  65 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'178\',\'通信一条街\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  66 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'179\',\'百货大楼商圈\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  67 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'180\',\'东地路\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  68 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'181\',\'宴宾楼\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  69 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'182\',\'服装城\',\'0\',\'173\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  70 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'184\',\'慢城\',\'0\',\'183\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  71 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'185\',\'华一\',\'0\',\'183\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  72 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'186\',\'扒鸡美食城\',\'0\',\'183\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  73 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'187\',\'勿忘我\',\'0\',\'183\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  74 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'188\',\'捷安特\',\'0\',\'183\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  75 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'189\',\'海尔\',\'0\',\'183\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  76 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'190\',\'梦特娇\',\'0\',\'183\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  77 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'192\',\'123\',\'0\',\'191\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  78 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'193\',\'456\',\'0\',\'191\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  79 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'198\',\'/upload/goods/20160110163220195.png\',\'0\',\'59\',\'0\',\'0\',\'0\',\'0\',\'新店开张\',\'0\')',
  80 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'202\',\'60分钟\',\'0\',\'200\',\'0\',\'0\',\'0\',\'0\',\'\',\'0\')',
  81 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'204\',\'59分钟送达\',\'0\',\'203\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  82 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'214\',\'订座\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  83 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'213\',\'点菜\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  84 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'212\',\'订台\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  85 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'211\',\'超市\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  86 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'210\',\'外卖\',\'0\',\'114\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  87 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'216\',\'酒水\',\'0\',\'215\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
  88 => 'INSERT INTO `xiaozu_shoptype`(`id`,`name`,`type`,`parent_id`,`cattype`,`is_search`,`is_main`,`is_admin`,`instro`,`orderid`) VALUES(\'217\',\'主食\',\'0\',\'215\',\'1\',\'0\',\'0\',\'0\',\'\',\'0\')',
)?>