<?php return array (
  0 => 'CREATE TABLE `xiaozu_shopsearch` (
  `shopid` int(20) NOT NULL,
  `parent_id` int(20) NOT NULL DEFAULT \'0\',
  `second_id` int(20) NOT NULL DEFAULT \'0\',
  `cattype` tinyint(1) NOT NULL DEFAULT \'0\' COMMENT \'1外卖2订台\'
) ENGINE=MyISAM DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'51\',\'73\',\'0\')',
  2 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'4\',\'51\',\'72\',\'0\')',
  3 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'214\',\'1\')',
  4 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'4\',\'51\',\'75\',\'0\')',
  5 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'4\',\'51\',\'112\',\'0\')',
  6 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'4\',\'51\',\'199\',\'0\')',
  7 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'213\',\'1\')',
  8 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'212\',\'1\')',
  9 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'211\',\'1\')',
  10 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'210\',\'1\')',
  11 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'159\',\'1\')',
  12 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'141\',\'1\')',
  13 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'117\',\'1\')',
  14 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'103\',\'114\',\'116\',\'1\')',
  15 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'195\',\'114\',\'212\',\'1\')',
  16 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'195\',\'114\',\'213\',\'1\')',
  17 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'198\',\'51\',\'75\',\'0\')',
  18 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'193\',\'51\',\'199\',\'0\')',
  19 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'193\',\'51\',\'75\',\'0\')',
  20 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'195\',\'114\',\'211\',\'1\')',
  21 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'195\',\'114\',\'210\',\'1\')',
  22 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'195\',\'114\',\'116\',\'1\')',
  23 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'195\',\'215\',\'217\',\'1\')',
  24 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'195\',\'215\',\'216\',\'1\')',
  25 => 'INSERT INTO `xiaozu_shopsearch`(`shopid`,`parent_id`,`second_id`,`cattype`) VALUES(\'197\',\'114\',\'211\',\'1\')',
)?>