<?php return array (
  0 => 'CREATE TABLE `xiaozu_rule` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT \'规则名称\',
  `type` int(1) NOT NULL COMMENT \'默认1，购物车总价\',
  `limittype` int(1) NOT NULL COMMENT \'是否指定具体时间1否2指定星期3指定小时\',
  `limittime` varchar(255) NOT NULL COMMENT \'具体时间：周几，或者具体时间\',
  `limitcontent` int(5) NOT NULL COMMENT \'限制内容购物车总价\',
  `controltype` int(1) NOT NULL COMMENT \'规则类型：1赠，3折扣，2减费用\',
  `controlcontent` int(20) DEFAULT NULL COMMENT \'限制内容填写赠品ID，折扣率，费用等大于0\',
  `starttime` int(11) NOT NULL COMMENT \'开始时间\',
  `endtime` int(11) NOT NULL COMMENT \'结束时间\',
  `status` tinyint(1) NOT NULL COMMENT \'状态1有效 2无效\',
  `shopid` int(20) NOT NULL COMMENT \'店铺id\',
  `presenttitle` varchar(255) DEFAULT NULL COMMENT \'赠品标题\',
  `signid` int(20) NOT NULL,
  `cattype` int(1) NOT NULL DEFAULT \'1\' COMMENT \'1外卖 2订台\',
  `supporttype` varchar(150) NOT NULL COMMENT \'支持类型：1首单有效，2在线支付有效\',
  `supportplatform` varchar(150) NOT NULL COMMENT \'支持平台：1pc端，2微信端，3触屏端，4客户端（安卓苹果）\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_rule`(`id`,`name`,`type`,`limittype`,`limittime`,`limitcontent`,`controltype`,`controlcontent`,`starttime`,`endtime`,`status`,`shopid`,`presenttitle`,`signid`,`cattype`,`supporttype`,`supportplatform`) VALUES(\'8\',\'满二十减一\',\'1\',\'2\',\'1,2,3,4,5\',\'20\',\'2\',\'1\',\'1452441600\',\'1483631999\',\'1\',\'4\',\'\',\'4\',\'0\',\'\',\'\')',
  2 => 'INSERT INTO `xiaozu_rule`(`id`,`name`,`type`,`limittype`,`limittime`,`limitcontent`,`controltype`,`controlcontent`,`starttime`,`endtime`,`status`,`shopid`,`presenttitle`,`signid`,`cattype`,`supporttype`,`supportplatform`) VALUES(\'9\',\'首单减2元\',\'1\',\'1\',\'\',\'0\',\'1\',\'19\',\'1452355200\',\'1483718399\',\'1\',\'4\',\'\',\'4\',\'0\',\'\',\'\')',
  3 => 'INSERT INTO `xiaozu_rule`(`id`,`name`,`type`,`limittype`,`limittime`,`limitcontent`,`controltype`,`controlcontent`,`starttime`,`endtime`,`status`,`shopid`,`presenttitle`,`signid`,`cattype`,`supporttype`,`supportplatform`) VALUES(\'11\',\'满50免配送费\',\'1\',\'1\',\'\',\'50\',\'4\',\'0\',\'1459094400\',\'1491753599\',\'1\',\'4\',\'\',\'7\',\'0\',\'\',\'\')',
)?>