<?php return array (
  0 => 'CREATE TABLE `xiaozu_shopattr` (
  `shopid` int(20) NOT NULL,
  `cattype` int(1) NOT NULL DEFAULT \'0\' COMMENT \'1外卖2订台\',
  `firstattr` int(20) NOT NULL DEFAULT \'0\',
  `attrid` int(20) NOT NULL DEFAULT \'0\' COMMENT \'该属性ID\',
  `value` varchar(255) DEFAULT NULL COMMENT \'值\'
) ENGINE=MyISAM DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'173\',\'0\',\'\')',
  2 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'127\',\'128\',\'自取\')',
  3 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'127\',\'129\',\'到店吃\')',
  4 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'130\',\'131\',\'自取\')',
  5 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'130\',\'132\',\'外卖\')',
  6 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'123\',\'124\',\'30\')',
  7 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'173\',\'175\',\'高地世纪城\')',
  8 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'183\',\'184\',\'慢城\')',
  9 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'100\',\'0\',\'30分钟\')',
  10 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'59\',\'198\',\'/upload/goods/20160110163220195.png\')',
  11 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'116\',\'杂货店\')',
  12 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'203\',\'0\',\'59分钟\')',
  13 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'184\',\'0\',\'51\',\'72\',\'网站专送\')',
  14 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'190\',\'0\',\'51\',\'73\',\'送药上门\')',
  15 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'192\',\'0\',\'51\',\'75\',\'美食外卖\')',
  16 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'59\',\'197\',\'/upload/goods/20160110163203632.png\')',
  17 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'200\',\'0\',\'30分钟\')',
  18 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'51\',\'112\',\'甜点饮品\')',
  19 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'51\',\'72\',\'网站专送\')',
  20 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'51\',\'199\',\'土豪馆\')',
  21 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'4\',\'0\',\'51\',\'75\',\'美食外卖\')',
  22 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'117\',\'综合商超\')',
  23 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'141\',\'五金店\')',
  24 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'159\',\'鮮花\')',
  25 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'214\',\'订座\')',
  26 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'213\',\'点菜\')',
  27 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'212\',\'订台\')',
  28 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'211\',\'超市\')',
  29 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'103\',\'1\',\'114\',\'210\',\'外卖\')',
  30 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'193\',\'1\',\'114\',\'116\',\'杂货店\')',
  31 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'197\',\'1\',\'114\',\'211\',\'超市\')',
  32 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'198\',\'0\',\'59\',\'196\',\'/upload/goods/20160110163208191.png\')',
  33 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'193\',\'0\',\'59\',\'196\',\'/upload/goods/20160110163208191.png\')',
  34 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'193\',\'0\',\'59\',\'197\',\'/upload/goods/20160110163203632.png\')',
  35 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'193\',\'0\',\'51\',\'199\',\'土豪馆\')',
  36 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'193\',\'0\',\'51\',\'75\',\'美食外卖\')',
  37 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'198\',\'0\',\'51\',\'75\',\'美食外卖\')',
  38 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'198\',\'0\',\'59\',\'197\',\'/upload/goods/20160110163203632.png\')',
  39 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'193\',\'0\',\'59\',\'195\',\'/upload/goods/20160110163214689.png\')',
  40 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'193\',\'0\',\'59\',\'198\',\'/upload/goods/20160110163220195.png\')',
  41 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'195\',\'1\',\'114\',\'116\',\'杂货店\')',
  42 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'195\',\'1\',\'114\',\'213\',\'点菜\')',
  43 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'195\',\'1\',\'114\',\'212\',\'订台\')',
  44 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'195\',\'1\',\'114\',\'211\',\'超市\')',
  45 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'195\',\'1\',\'114\',\'210\',\'外卖\')',
  46 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'195\',\'1\',\'215\',\'216\',\'酒水\')',
  47 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'195\',\'1\',\'215\',\'217\',\'主食\')',
  48 => 'INSERT INTO `xiaozu_shopattr`(`shopid`,`cattype`,`firstattr`,`attrid`,`value`) VALUES(\'199\',\'0\',\'51\',\'75\',\'美食外卖\')',
)?>