<?php return array (
  0 => 'CREATE TABLE `xiaozu_goodslibrarycate` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL COMMENT \'分类名称\',
  `orderid` int(3) NOT NULL DEFAULT \'0\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=54 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'43\',\'绝味鸭脖\',\'13\')',
  2 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'11\',\'下午茶\',\'7\')',
  3 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'10\',\'西餐\',\'6\')',
  4 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'41\',\'黄焖鸡\',\'11\')',
  5 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'9\',\'水果\',\'5\')',
  6 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'42\',\'大脸鸡排\',\'12\')',
  7 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'8\',\'鲜花\',\'7\')',
  8 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'34\',\'中餐\',\'4\')',
  9 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'35\',\'蛋糕\',\'5\')',
  10 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'53\',\'土大力\',\'20\')',
  11 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'39\',\'肯德基\',\'9\')',
  12 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'40\',\'必胜客\',\'10\')',
  13 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'44\',\'凉皮\',\'14\')',
  14 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'45\',\'揽锅菜\',\'15\')',
  15 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'46\',\'土匪菜\',\'16\')',
  16 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'47\',\'饺子\',\'17\')',
  17 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'48\',\'饮料\',\'18\')',
  18 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'49\',\'精品推荐\',\'19\')',
  19 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'50\',\'凉菜系列\',\'20\')',
  20 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'51\',\'食品零食\',\'21\')',
  21 => 'INSERT INTO `xiaozu_goodslibrarycate`(`id`,`name`,`orderid`) VALUES(\'52\',\'酒品类\',\'22\')',
)?>