<?php return array (
  0 => 'CREATE TABLE `xiaozu_shop` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `uid` int(20) NOT NULL COMMENT \'用户ID\',
  `shortname` varchar(10) DEFAULT NULL COMMENT \'店铺短地址\',
  `shopname` varchar(150) NOT NULL COMMENT \'店铺名称\',
  `shoplogo` varchar(150) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL COMMENT \'联系电话\',
  `address` varchar(150) DEFAULT NULL COMMENT \'联系地址\',
  `point` int(10) NOT NULL DEFAULT \'5\' COMMENT \'评分\',
  `cx_info` text COMMENT \'促销信息\',
  `intr_info` text COMMENT \'介绍信息\',
  `notice_info` text COMMENT \'公告信息\',
  `starttime` varchar(100) DEFAULT NULL COMMENT \'营业时间\',
  `is_open` int(1) NOT NULL DEFAULT \'0\' COMMENT \'是否营业\',
  `is_onlinepay` int(1) NOT NULL DEFAULT \'1\' COMMENT \'是否开启在线支付：默认为1开启，0不开启\',
  `is_daopay` int(1) NOT NULL DEFAULT \'1\' COMMENT \'是否开启到付：默认为1开启，0不开启\',
  `is_pass` int(1) NOT NULL DEFAULT \'0\' COMMENT \'是否通过审核\',
  `is_recom` int(1) NOT NULL DEFAULT \'0\' COMMENT \'是否是推荐店铺\',
  `maphone` varchar(12) DEFAULT NULL,
  `addtime` int(12) DEFAULT NULL,
  `pointcount` int(5) NOT NULL DEFAULT \'0\',
  `psservicepoint` int(11) NOT NULL COMMENT \'配送服务评分\',
  `psservicepointcount` int(11) NOT NULL COMMENT \'配送服务评论次数\',
  `yjin` decimal(5,2) NOT NULL DEFAULT \'0.00\' COMMENT \'佣金比例当为0时调用网站设置\',
  `lat` decimal(9,6) NOT NULL DEFAULT \'0.000000\' COMMENT \'地图左坐标\',
  `lng` decimal(9,6) NOT NULL DEFAULT \'0.000000\' COMMENT \'地图右坐标\',
  `shopbacklogo` varchar(255) DEFAULT NULL COMMENT \'商家默认背景图片\',
  `sort` int(20) NOT NULL DEFAULT \'999\' COMMENT \'排序\',
  `email` varchar(50) DEFAULT NULL,
  `areaid1` int(20) NOT NULL DEFAULT \'0\',
  `areaid2` int(20) NOT NULL DEFAULT \'0\',
  `areaid3` int(20) NOT NULL DEFAULT \'0\',
  `otherlink` varchar(255) DEFAULT NULL COMMENT \'其他链接地址\',
  `endtime` int(11) NOT NULL DEFAULT \'0\',
  `IMEI` varchar(255) DEFAULT NULL,
  `shoptype` int(2) NOT NULL DEFAULT \'0\',
  `noticetype` varchar(100) DEFAULT NULL,
  `machine_code` varchar(255) DEFAULT NULL COMMENT \'打印2机器码\',
  `mKey` varchar(255) DEFAULT NULL COMMENT \'打印2打印密匙\',
  `pradiusa` int(1) NOT NULL DEFAULT \'1\',
  `admin_id` int(20) NOT NULL DEFAULT \'0\',
  `sellcount` int(10) DEFAULT \'0\',
  `goodattrdefault` varchar(25) NOT NULL,
  `ruzhutype` int(11) NOT NULL DEFAULT \'0\',
  `qiyeimg` varchar(150) NOT NULL,
  `zmimg` varchar(150) NOT NULL,
  `fmimg` varchar(150) NOT NULL,
  `foodtongimg` varchar(150) DEFAULT NULL,
  `jkzimg` varchar(150) DEFAULT NULL,
  `sqimg` varchar(150) DEFAULT NULL,
  `qtshuoming` varchar(255) DEFAULT NULL,
  `wxhui_ewmurl` text NOT NULL COMMENT \'闪惠制作二维码url\',
  `goodlistmodule` int(1) NOT NULL DEFAULT \'0\' COMMENT \'商品列表模板默认为0   \',
  `shoplicense` varchar(150) NOT NULL COMMENT \'营业执照\',
  `virtualsellcounts` int(11) DEFAULT NULL COMMENT \'店铺虚拟总销量\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=200 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_shop`(`id`,`uid`,`shortname`,`shopname`,`shoplogo`,`phone`,`address`,`point`,`cx_info`,`intr_info`,`notice_info`,`starttime`,`is_open`,`is_onlinepay`,`is_daopay`,`is_pass`,`is_recom`,`maphone`,`addtime`,`pointcount`,`psservicepoint`,`psservicepointcount`,`yjin`,`lat`,`lng`,`shopbacklogo`,`sort`,`email`,`areaid1`,`areaid2`,`areaid3`,`otherlink`,`endtime`,`IMEI`,`shoptype`,`noticetype`,`machine_code`,`mKey`,`pradiusa`,`admin_id`,`sellcount`,`goodattrdefault`,`ruzhutype`,`qiyeimg`,`zmimg`,`fmimg`,`foodtongimg`,`jkzimg`,`sqimg`,`qtshuoming`,`wxhui_ewmurl`,`goodlistmodule`,`shoplicense`,`virtualsellcounts`) VALUES(\'193\',\'1112\',\'\',\'外卖旗舰店\',\'/upload/user/20160908200438759.jpg\',\'15741203669\',\'河南省郑州市中原区湖西路\',\'5\',\'\',\'\',\'\',\'08:00-12:00|12:02-23:59\',\'1\',\'1\',\'1\',\'1\',\'1\',\'15741203669\',\'0\',\'0\',\'0\',\'0\',\'10.00\',\'34.766936\',\'113.582633\',\'\',\'999\',\'\',\'0\',\'0\',\'0\',\'\',\'1504866420\',\'\',\'0\',\'1,2,3\',\'\',\'\',\'1\',\'90\',\'5\',\'件\',\'0\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'0\',\'\',\'0\')',
  2 => 'INSERT INTO `xiaozu_shop`(`id`,`uid`,`shortname`,`shopname`,`shoplogo`,`phone`,`address`,`point`,`cx_info`,`intr_info`,`notice_info`,`starttime`,`is_open`,`is_onlinepay`,`is_daopay`,`is_pass`,`is_recom`,`maphone`,`addtime`,`pointcount`,`psservicepoint`,`psservicepointcount`,`yjin`,`lat`,`lng`,`shopbacklogo`,`sort`,`email`,`areaid1`,`areaid2`,`areaid3`,`otherlink`,`endtime`,`IMEI`,`shoptype`,`noticetype`,`machine_code`,`mKey`,`pradiusa`,`admin_id`,`sellcount`,`goodattrdefault`,`ruzhutype`,`qiyeimg`,`zmimg`,`fmimg`,`foodtongimg`,`jkzimg`,`sqimg`,`qtshuoming`,`wxhui_ewmurl`,`goodlistmodule`,`shoplicense`,`virtualsellcounts`) VALUES(\'195\',\'2954\',\'\',\'粮油超市\',\'/upload/user/20160908184721145.jpg\',\'15740369887\',\'河南省郑州市中原区湖西路\',\'5\',\'\',\'\',\'\',\'08:00-12:00|12:03-23:58\',\'1\',\'1\',\'1\',\'1\',\'1\',\'15740369887\',\'1473330845\',\'0\',\'0\',\'0\',\'0.00\',\'32.064735\',\'118.802891\',\'\',\'999\',\'shop2@163.com\',\'0\',\'0\',\'0\',\'\',\'1504866845\',\'\',\'1\',\'1,2,3\',\'\',\'\',\'0\',\'0\',\'0\',\'个\',\'0\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'0\',\'\',\'0\')',
  3 => 'INSERT INTO `xiaozu_shop`(`id`,`uid`,`shortname`,`shopname`,`shoplogo`,`phone`,`address`,`point`,`cx_info`,`intr_info`,`notice_info`,`starttime`,`is_open`,`is_onlinepay`,`is_daopay`,`is_pass`,`is_recom`,`maphone`,`addtime`,`pointcount`,`psservicepoint`,`psservicepointcount`,`yjin`,`lat`,`lng`,`shopbacklogo`,`sort`,`email`,`areaid1`,`areaid2`,`areaid3`,`otherlink`,`endtime`,`IMEI`,`shoptype`,`noticetype`,`machine_code`,`mKey`,`pradiusa`,`admin_id`,`sellcount`,`goodattrdefault`,`ruzhutype`,`qiyeimg`,`zmimg`,`fmimg`,`foodtongimg`,`jkzimg`,`sqimg`,`qtshuoming`,`wxhui_ewmurl`,`goodlistmodule`,`shoplicense`,`virtualsellcounts`) VALUES(\'197\',\'2955\',\'\',\'大润发超市旗舰店\',\'/upload/user/20161014175158823.jpg\',\'15741023669\',\'河南省郑州市中原区湖西路\',\'5\',\'\',\'店铺数据仅供测试使用......\',\'数据仅供测试使用......\',\'08:00-12:00|12:02-23:58\',\'1\',\'1\',\'1\',\'1\',\'0\',\'15741023669\',\'1473331855\',\'0\',\'0\',\'0\',\'0.00\',\'34.766936\',\'113.582633\',\'\',\'999\',\'links90@163.com\',\'0\',\'0\',\'0\',\'\',\'1504867855\',\'\',\'1\',\'\',\'\',\'\',\'1\',\'0\',\'0\',\'个\',\'0\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'0\',\'\',\'0\')',
  4 => 'INSERT INTO `xiaozu_shop`(`id`,`uid`,`shortname`,`shopname`,`shoplogo`,`phone`,`address`,`point`,`cx_info`,`intr_info`,`notice_info`,`starttime`,`is_open`,`is_onlinepay`,`is_daopay`,`is_pass`,`is_recom`,`maphone`,`addtime`,`pointcount`,`psservicepoint`,`psservicepointcount`,`yjin`,`lat`,`lng`,`shopbacklogo`,`sort`,`email`,`areaid1`,`areaid2`,`areaid3`,`otherlink`,`endtime`,`IMEI`,`shoptype`,`noticetype`,`machine_code`,`mKey`,`pradiusa`,`admin_id`,`sellcount`,`goodattrdefault`,`ruzhutype`,`qiyeimg`,`zmimg`,`fmimg`,`foodtongimg`,`jkzimg`,`sqimg`,`qtshuoming`,`wxhui_ewmurl`,`goodlistmodule`,`shoplicense`,`virtualsellcounts`) VALUES(\'198\',\'2956\',\'\',\'云爸爸KFC\',\'/upload/user/20160908190814504.jpg\',\'15741036998\',\'河南省郑州市中原区湖西路\',\'5\',\'\',\'\',\'\',\'08:00-14:30|14:50-23:59\',\'1\',\'1\',\'1\',\'1\',\'1\',\'15741036998\',\'1473332698\',\'0\',\'0\',\'0\',\'0.00\',\'34.766936\',\'113.582633\',\'\',\'999\',\'kfc90@163.com\',\'0\',\'0\',\'0\',\'\',\'1504868698\',\'\',\'0\',\'1,2,3\',\'\',\'\',\'0\',\'0\',\'0\',\'份\',\'0\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'0\',\'\',\'0\')',
  5 => 'INSERT INTO `xiaozu_shop`(`id`,`uid`,`shortname`,`shopname`,`shoplogo`,`phone`,`address`,`point`,`cx_info`,`intr_info`,`notice_info`,`starttime`,`is_open`,`is_onlinepay`,`is_daopay`,`is_pass`,`is_recom`,`maphone`,`addtime`,`pointcount`,`psservicepoint`,`psservicepointcount`,`yjin`,`lat`,`lng`,`shopbacklogo`,`sort`,`email`,`areaid1`,`areaid2`,`areaid3`,`otherlink`,`endtime`,`IMEI`,`shoptype`,`noticetype`,`machine_code`,`mKey`,`pradiusa`,`admin_id`,`sellcount`,`goodattrdefault`,`ruzhutype`,`qiyeimg`,`zmimg`,`fmimg`,`foodtongimg`,`jkzimg`,`sqimg`,`qtshuoming`,`wxhui_ewmurl`,`goodlistmodule`,`shoplicense`,`virtualsellcounts`) VALUES(\'199\',\'2966\',\'\',\'测试店铺\',\'/upload/user/20161014174817921.jpg\',\'15874102410\',\'河南省郑州市\',\'5\',\'\',\'\',\'\',\'08:00-14:30\',\'1\',\'1\',\'1\',\'1\',\'0\',\'15874102410\',\'1476416403\',\'0\',\'0\',\'0\',\'0.00\',\'34.796651\',\'113.591247\',\'\',\'999\',\'ceshi@163.com\',\'0\',\'0\',\'0\',\'\',\'1507952403\',\'\',\'0\',\'\',\'\',\'\',\'1\',\'0\',\'0\',\'份\',\'0\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'\',\'0\',\'\',\'\')',
)?>