<?php return array (
  0 => 'CREATE TABLE `xiaozu_news` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `content` text NOT NULL,
  `addtime` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `typeid` int(2) NOT NULL,
  `orderid` int(5) NOT NULL DEFAULT \'1000\' COMMENT \'1000\',
  `seo_key` varchar(255) DEFAULT NULL,
  `seo_content` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=16 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'7\',\'现在国内的外卖市场极其火爆，各个平台凭借地理优势悄然占据市场，分食市场份额。利用大的环境趋势去完成自己创业梦想。光合科技完全独立自主研发的外卖人订餐系统来帮助您，国内第一外卖订餐系统，为您提供外卖行业的全套解决方案，帮助创业者们搭建外卖网站，完成创业梦想，您向成功又迈近了一步。\',\'1436544000\',\'订单支付\',\'3\',\'4\',\'做外卖平台找外卖人订餐系统\',\'外卖市场火爆，外卖人订餐系统也很火爆，价格优惠的外卖人订餐系统给创业者们提供外卖行业的全套解决方案\')',
  2 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'8\',\'各位尊敬的创业者们你们好，为了解决您对技术方面的后顾之忧，我们光合科技郑重承诺，我们为您提供终身免费的一个网站升级服务。解决您的后顾之忧，让您能放开手脚去大干一番，对，我们就是您起飞的翅膀。\',\'1436544000\',\'配送说明\',\'4\',\'3\',\'外卖人订餐系统提供终身免费升级服务\',\'外卖人订餐系统提供终身免费升级服务。光合科技外卖人订餐平台开发团队承诺您，我们外卖人订餐系统平台提供终身免费升级的服务\')',
  3 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'10\',\'<ul class=\\"tabs\\" style=\\"margin:0px;padding:0px;font-family:\\\'Microsoft YaHei\\\', SimSun, Arial;border-width:0px 0px 1px;border-style:none none solid;border-bottom-color:#e0e1e2;list-style:none;width:1060px;height:41px;color:#333333;line-height:normal;background-color:#f5f5f5;\\"><li class=\\"checked\\" style=\\"margin:1px 0px 0px;padding:0px;list-style:none;border-width:1px 1px 0px;border-top-style:solid;border-right-style:solid;border-left-style:solid;border-top-color:#ffffff;border-right-color:#ffffff;border-left-color:#ffffff;float:left;width:200px;height:40px;text-align:center;line-height:40px;font-size:20px;color:#3f7cc2;cursor:pointer;border-radius:4px;background-image:initial;background-attachment:initial;background-size:initial;background-origin:initial;background-clip:initial;background-position:initial;background-repeat:initial;\\"><span style=\\"margin:0px;padding:0px;width:198px;height:39px;display:block;line-height:39px;color:#3c7bc5;cursor:pointer;border-radius:4px;border-width:1px 1px 0px;border-top-style:solid;border-right-style:solid;border-left-style:solid;border-top-color:#e0e1e2;border-right-color:#e0e1e2;border-left-color:#e0e1e2;\\">后台功能说明</span></li>
<li style=\\"margin:1px 0px 0px;padding:0px;list-style:none;border-width:0px 0px 1px;border-style:none none solid;border-bottom-color:#e0e1e2;float:left;width:200px;height:40px;text-align:center;line-height:40px;font-size:20px;color:#666666;cursor:pointer;\\"><a href=\\"http://www.waimairen.com/support/index/belongid/6\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#666666;\\">商家后台说明</a></li>
<li style=\\"margin:1px 0px 0px;padding:0px;list-style:none;border-width:0px 0px 1px;border-style:none none solid;border-bottom-color:#e0e1e2;float:left;width:200px;height:40px;text-align:center;line-height:40px;font-size:20px;color:#666666;cursor:pointer;\\"><a href=\\"http://www.waimairen.com/support/index/belongid/18\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#666666;\\">手机网站</a></li>
</ul>
<div class=\\"tabbox_underline\\" style=\\"margin:0px;padding:0px;font-family:\\\'Microsoft YaHei\\\', SimSun, Arial;width:1060px;height:1px;border-top-width:1px;border-top-style:solid;border-top-color:#ffffff;position:absolute;top:40px;left:0px;z-index:-5;color:#333333;line-height:normal;background-color:#f5f5f5;\\"></div>
<div class=\\"tab_conbox\\" style=\\"margin:20px 0px 10px;padding:0px;font-family:\\\'Microsoft YaHei\\\', SimSun, Arial;width:1060px;overflow:hidden;color:#333333;line-height:normal;background-color:#f5f5f5;\\"><div class=\\"tab_con\\" style=\\"margin:0px;padding:0px;width:1060px;overflow:hidden;\\"><div class=\\"tab_con_listBox\\" style=\\"margin:0px;padding:15px 0px;width:240px;overflow:hidden;float:left;position:relative;background:url(http://www.waimairen.com/templates/default/public/images/icon_shadow.png) 225px 0px repeat-y;\\"><div class=\\"tab_con_list\\" style=\\"margin:0px;padding:0px;width:200px;overflow:hidden;float:left;\\"><dl style=\\"margin:0px;padding:0px;border:0px none;width:200px;overflow:hidden;float:left;\\"><dt style=\\"margin:0px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:32px;color:#666666;font-size:15px;text-indent:57px;position:relative;cursor:pointer;\\"><div class=\\"tab_con_icon icon_open\\" is_expansion=\\"true\\" style=\\"margin:0px;padding:0px;width:13px;height:13px;position:absolute;top:10px;left:37px;cursor:pointer;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -541px -154px no-repeat;\\"></div>
基础功能</dt><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/100\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">外卖人5.0版本</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/101\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">网站限制</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/102\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">积分设置</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/103\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">导航管理</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/104\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">管理员权限</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/105\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">店铺列表</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/106\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">店铺标签</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/107\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">私信管理</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/108\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">优惠券管理</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/109\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">充值卡管理</a></dd><dd class=\\"checked\\" style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;color:#3f7cc2;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
群发任务</dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/111\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">登陆接口</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/112\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">短信邮箱模板</a></dd><dd style=\\"margin:0px 0px 2px;padding:0px;border:0px none;width:200px;overflow:hidden;line-height:25px;text-indent:73px;font-size:14px;white-space:nowrap;position:relative;\\"><div class=\\"icon_news\\" style=\\"margin:0px;padding:0px;position:absolute;top:10px;left:60px;width:4px;height:4px;background:url(http://www.waimairen.com/templates/default/public/images/img.png) -560px -6px no-repeat;\\"></div>
<a href=\\"http://www.waimairen.com/support/index/showid/126\\" style=\\"margin:0px;padding:0px;text-decoration:none;color:#888888;width:auto;overflow:hidden;\\">商家结算</a></dd></dl></div>
<div class=\\"tab_con_TopShadow\\" style=\\"margin:0px;padding:0px;width:25px;height:65px;position:absolute;top:0px;left:225px;background:url(http://www.waimairen.com/templates/default/public/images/topshadow.png);\\"></div>
<div class=\\"tab_con_BottomShadow\\" style=\\"margin:0px;padding:0px;width:25px;height:65px;position:absolute;left:225px;bottom:0px;background:url(http://www.waimairen.com/templates/default/public/images/bottomshadow.png);\\"></div>
</div>
<div class=\\"tab_con_content\\" style=\\"margin:0px;padding:0px;width:800px;overflow:hidden;float:right;\\"><span class=\\"tab_con_title\\" style=\\"margin:0px 0px 10px;padding:0px;font-size:26px;color:#64666d;line-height:60px;text-align:center;\\">群发</span></div>
</div>
</div>\',\'1438617600\',\'退货说明\',\'4\',\'2\',\'退货说明\',\'///48/58//\')',
  4 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'11\',\'外卖人网上订餐系统8.0发布上线！\',\'1438704000\',\'联系我们\',\'15\',\'1\',\'外卖人\',\'外卖人网上订餐\')',
  5 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'12\',\'用户下单流程\',\'1452355200\',\'下单流程\',\'3\',\'0\',\'\',\'\')',
  6 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'13\',\'订单支付方式\',\'1452355200\',\'支付方式\',\'3\',\'0\',\'\',\'\')',
  7 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'14\',\'联系我们\',\'1452355200\',\'网站介绍\',\'15\',\'0\',\'\',\'\')',
  8 => 'INSERT INTO `xiaozu_news`(`id`,`content`,`addtime`,`title`,`typeid`,`orderid`,`seo_key`,`seo_content`) VALUES(\'15\',\'物流服务\',\'1452355200\',\'物流服务\',\'4\',\'0\',\'\',\'\')',
)?>