<?php return array (
  0 => 'CREATE TABLE `xiaozu_orderdet` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `order_id` int(20) NOT NULL,
  `goodsid` int(20) NOT NULL,
  `goodsname` varchar(150) NOT NULL,
  `goodscost` decimal(10,2) NOT NULL,
  `goodscount` int(2) NOT NULL,
  `status` int(1) NOT NULL DEFAULT \'0\',
  `shopid` int(5) NOT NULL,
  `is_send` int(11) NOT NULL DEFAULT \'0\' COMMENT \'是否是赠品 1赠品\',
  `product_id` int(20) NOT NULL DEFAULT \'0\',
  `have_det` int(1) NOT NULL DEFAULT \'0\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=50 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'1\',\'1\',\'871\',\'虾仁面\',\'30.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  2 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'2\',\'1\',\'1031\',\'麻辣豆腐盖饭【小份】\',\'8.00\',\'2\',\'0\',\'4\',\'0\',\'46\',\'1\')',
  3 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'3\',\'2\',\'1031\',\'麻辣豆腐盖饭【小份】\',\'8.00\',\'1\',\'1\',\'4\',\'0\',\'46\',\'1\')',
  4 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'4\',\'2\',\'1520\',\'黄焖鸡【小份,特辣】\',\'10.00\',\'1\',\'1\',\'4\',\'0\',\'111\',\'1\')',
  5 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'5\',\'2\',\'1522\',\'红烧肉刀削面\',\'8.00\',\'2\',\'1\',\'4\',\'0\',\'0\',\'0\')',
  6 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'6\',\'2\',\'1524\',\'烧腐竹\',\'10.00\',\'1\',\'1\',\'4\',\'0\',\'0\',\'0\')',
  7 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'7\',\'3\',\'868\',\'清汤面\',\'10.00\',\'3\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  8 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'8\',\'4\',\'868\',\'清汤面\',\'10.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  9 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'9\',\'4\',\'875\',\'炸酱面\',\'15.00\',\'2\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  10 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'10\',\'4\',\'867\',\'牛肉盖浇饭【大份】\',\'41.00\',\'5\',\'0\',\'4\',\'0\',\'51\',\'1\')',
  11 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'11\',\'4\',\'867\',\'牛肉盖浇饭【小份】\',\'31.00\',\'1\',\'0\',\'4\',\'0\',\'52\',\'1\')',
  12 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'12\',\'8\',\'875\',\'炸酱面\',\'15.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  13 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'13\',\'8\',\'1522\',\'红烧肉刀削面\',\'8.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  14 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'14\',\'9\',\'1522\',\'红烧肉刀削面\',\'8.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  15 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'15\',\'9\',\'1523\',\'烧青菜这是个长名字超出的话要隐藏哦\',\'10.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  16 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'16\',\'10\',\'1615\',\'多口味素牛肉\',\'8.00\',\'1\',\'0\',\'103\',\'0\',\'0\',\'0\')',
  17 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'17\',\'10\',\'1616\',\'香辣鸭脖32g/袋\',\'5.00\',\'1\',\'0\',\'103\',\'0\',\'0\',\'0\')',
  18 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'18\',\'11\',\'1615\',\'多口味素牛肉\',\'8.00\',\'1\',\'0\',\'103\',\'0\',\'0\',\'0\')',
  19 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'19\',\'11\',\'1616\',\'香辣鸭脖32g/袋\',\'5.00\',\'1\',\'0\',\'103\',\'0\',\'0\',\'0\')',
  20 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'20\',\'12\',\'1523\',\'烧青菜这是个长名字超出的话要隐藏哦\',\'10.00\',\'2\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  21 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'21\',\'12\',\'9\',\'\',\'0.00\',\'1\',\'0\',\'4\',\'1\',\'0\',\'0\')',
  22 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'22\',\'13\',\'1540\',\'腊八豆角脆骨\',\'25.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  23 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'23\',\'14\',\'1541\',\'萝卜干炒腊肉\',\'25.00\',\'1\',\'0\',\'4\',\'0\',\'0\',\'0\')',
  24 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'24\',\'15\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  25 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'25\',\'16\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  26 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'26\',\'17\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  27 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'27\',\'17\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  28 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'28\',\'18\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  29 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'29\',\'18\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  30 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'30\',\'19\',\'1716\',\'香辣鸭脖32g/袋\',\'5.00\',\'1\',\'0\',\'195\',\'0\',\'0\',\'0\')',
  31 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'31\',\'19\',\'1717\',\'清真锅巴香脆\',\'5.00\',\'1\',\'0\',\'195\',\'0\',\'0\',\'0\')',
  32 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'32\',\'20\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  33 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'33\',\'20\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'2\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  34 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'34\',\'21\',\'1701\',\'平菇炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  35 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'35\',\'21\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  36 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'36\',\'21\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  37 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'37\',\'22\',\'1710\',\'拌鸡拌虾堡\',\'30.00\',\'1\',\'0\',\'198\',\'0\',\'0\',\'0\')',
  38 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'38\',\'22\',\'1711\',\'劲爆鸡腿堡\',\'28.00\',\'1\',\'0\',\'198\',\'0\',\'0\',\'0\')',
  39 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'39\',\'23\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'2\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  40 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'40\',\'24\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'2\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  41 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'41\',\'25\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  42 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'42\',\'25\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'2\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  43 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'43\',\'26\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  44 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'44\',\'26\',\'1703\',\'蒜苗炒肉\',\'18.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  45 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'45\',\'27\',\'1701\',\'平菇炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  46 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'46\',\'28\',\'1711\',\'劲爆鸡腿堡\',\'28.00\',\'1\',\'0\',\'198\',\'0\',\'0\',\'0\')',
  47 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'47\',\'29\',\'1702\',\'韭菜炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  48 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'48\',\'30\',\'1701\',\'平菇炒蛋\',\'8.00\',\'1\',\'0\',\'193\',\'0\',\'0\',\'0\')',
  49 => 'INSERT INTO `xiaozu_orderdet`(`id`,`order_id`,`goodsid`,`goodsname`,`goodscost`,`goodscount`,`status`,`shopid`,`is_send`,`product_id`,`have_det`) VALUES(\'49\',\'31\',\'1707\',\'旺旺O泡果奶\',\'8.00\',\'1\',\'0\',\'195\',\'0\',\'0\',\'0\')',
)?>